// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ErrorCalculation: typeof import('./src/components/ErrorCalculation.vue')['default']
    InputData: typeof import('./src/components/InputData.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheMain: typeof import('./src/components/TheMain.vue')['default']
  }
}
